### ISSUE TITLE
Maquina de cupom?

### ISSUE THREAD

**Issue by Marechaos** [gnstrg/slashbot#1]
Dei uma olhada e o bot é super rápido, parabéns, existe a chance de adaptar ele para pegar cupom também?

**Comment by jeffesonjel** [comment]
poderia me explica como faço para ele parar de dar "erro ao criar conta" ?

**Comment by eikerb** [comment]
o pora fechei sem querer

**Comment by eikerb** [comment]
sim vou ver esse negocio do cupom

**Comment by eikerb** [comment]
esse erro ocorre quando vc nao bota oque vai começar o email 
"what word does the email start with?" é pra vc colocar que no vc quisser exemplo what word does the email start with? rolnado
na hora que for criar o email vai ser rolnado.nomealeatorio@gmail.com entendeu?

**Comment by jeffesonjel** [comment]
ok irei testar 
se funcionar eu falei 
edit: error slash menu( esse é o novo erro)

**Comment by eikerb** [comment]
to refazendo o bot do zero com o playwright vou fazer ele nao dá dando erro como o selenium faz
